### ISSUE TITLE
Erreur certbot

### ISSUE THREAD

**Issue by welcoMattic** [bilyboy785/seedbox-compose#2]
```
includes/functions.sh: line 449: ./includes/certbot/certbot-auto: No such file or directory
		* Certificate generation failed !
```

**Comment by bilyboy785** [comment]
Vous avez lancé le script depuis le répertoire seedbox-compose ?

**Comment by welcoMattic** [comment]
Hmm bonne question, j'ai fait ça en même temps que 10 autres trucs. Je vais revoir ça dans la journée

**Comment by bilyboy785** [comment]
Le script certbot est sous $PWD/seedbox-compose/includes/certbot/certbot-auto.

Il faut que je prenne en compte le fait que le clonage de mon repo puisse se faire ailleurs. Je vais rajouter au menu principal la possibilité de regenerer des certificats.

**Comment by welcoMattic** [comment]
J'ai cloné seedbox-compose dans `/home/my_user/`

**Comment by bilyboy785** [comment]
Le script créé l'utilisateur. Il est donc préférable de démarrer sur une distrib fresh, sans user, de cloner le repo genre sous /root puis de lancer le script. Mais bonne remarque, je vais prendre en compte le fait que l'utilisateur possède déjà un utilisateur.

**Comment by welcoMattic** [comment]
J'ai réussi à faire générer les certificats, mais ils sont générés pour (pa exemple):

`sonarr.mydomain.tld.mydomain.tld`

**Comment by welcoMattic** [comment]
Pour gérer différentes app dans des containers, j'utilise https://traefik.io. C'est hyper simple à configurer

**Comment by bilyboy785** [comment]
Le problème est corrigé pour la génération des certificats. 
Je vais me pencher sur Traefik ;)
