### ISSUE TITLE
Nginx CNAME + intégration d'un watcher pour update

### ISSUE THREAD

**Issue by Antexa** [bilyboy785/seedbox-compose#7]
Sympa ce script, il est super lisible.

Concernant les mises à jour des conteneurs pourquoi ne pas intégrer un watcher comme : 
https://github.com/v2tec/watchtower
Sinon comment prendre en compte les updates ? 

Autre question, je n'utilise pas de CNAME pour la partie nginx, que me conseilles-tu pour passer via des URI directement en proxy_pass sous nginx (fqdn.lan/**ressource**)

**Comment by bilyboy785** [comment]
Merci à toi ! 

Pas de CNAME, mais un nom de domaine ? Ou tu compte en avoir une utilisation en local ?

**Comment by bilyboy785** [comment]
Je viens d'intégrer WatchTower ;) ça a l'air sympa en effet !

**Comment by Antexa** [comment]
Pardon un CNAME pour moi est un sous domaine : 
**ressource**.fqdn.com
**ressource1**.fqdn.com

Je préfère cette construction niveau nginx : 
fqdn.com/**ressource**
fqdn.com/**ressource1**

L'interet est d'avoir uniquement un seul certificat qui porte plusieurs ressources

**Comment by bilyboy785** [comment]
Ah oui en effet ! 
Je termine mes tests sur la branch dev et te confirme quand c'est OK sur La master.

**Comment by bilyboy785** [comment]
La branch master est ok ;)
Du coup merci encore pour WatchTower et j'ai ajouté les URI
