### ISSUE TITLE
Verification DNS Entry

### ISSUE THREAD

**Issue by Antexa** [bilyboy785/seedbox-compose#9]
Quand tu vérifies l'IP de la machine, tu ne récupères pas l'IP publique mais l'IPA de l'eth0 si je ne dis pas de bêtise. 

Du coup dans un réseau NATé on rentre dans une boucle de vérification.

Est-il possible de la désactiver ?

**Comment by bilyboy785** [comment]
Désactiver la vérification de l'adresse IP ?

**Comment by Antexa** [comment]
Il s'agit d'une vérification qui intervient après la sélection des applications dans le workflow, elle me demande de créer une entrée A avec l'IP X.X.X.X, le problème c'est que l'IP qui semble attendu est l'IP Privé et non pas mon IP Publique.

`ping -c 1 $DOMAINSSL | grep "$IPADDRESS" > /dev/null
`

A la place du ping, tu peux essayer cette commande qui sera plus ciblée par rapport au DNS

`WANIP=$(dig o-o.myaddr.l.google.com @ns1.google.com txt +short | sed 's/"//g')`

**Comment by bilyboy785** [comment]
Ah oui en effet, je n'avais pas pensé à ca ! :) 

Je vais voir pour intégrer ce que tu viens de me donner ;)

**Comment by Antexa** [comment]
Sans problème, 

Tiens moi au courant :+1:

**Comment by bilyboy785** [comment]
C'est bon j'ai intégré ta solution [c976a85](https://github.com/bilyboy785/seedbox-compose/commit/044aae7f7f8c687b6a5601b564cc4de597c996a3).

Il me reste quelques test et modifications et je merge vers la branch master ;)

**Comment by Antexa** [comment]
Hello, 

J'ai vite fait tester sur une debian from scratch et mon installatio n'avait pas dig par défaut. 

Peux-tu rajouter la paquet suivant lors de l'installation des pré-requis ?

**dnsutils
